import { activeNav } from './js/handleSubmit'
import { restingNav } from './js/handleSubmit'
import { handleSubmit } from './js/handleSubmit'
import { checkURL } from './js/checkURL'
import { sendData } from './js/sendData'
import { updateUI } from './js/updateUI'
import { restingNav } from './js/mobileNav'
import { activeNav } from './js/mobileNav'

import './styles/resets.scss'
import './styles/base.scss'
import './styles/form.scss'
import './styles/header.scss'